import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { NextThemeProvider } from "@/components/NextThemeProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning className="light">
      <body className={inter.className}>
        <NextThemeProvider >{children}</NextThemeProvider>
      </body>
    </html>
  );
}
